name: Cygport Packager for h8300-hitachi-coff-toolchain

on:
  workflow_dispatch:
  schedule:
    # Following POSIX cron syntax, run every Monday morning at 5:30 AM UTC
    #   https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron:   '30 5 * * 1'
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

env:
  REPO_DIR:     BrickBot
  PROJECT_NAME: h8300-hitachi-coff-toolchain
  # The name of the Cyport file is the same as github.repository
  CYGPORT_FILE: ${{ github.repository }}
  PACKAGE_PATH: "h8300*-coff-toolchain-*.*.*-*.*/dist/h8300-hitachi-coff-toolchain/h8300*-coff-toolchain-*.*.*-*.*.tar.xz"
  
  # Prevent the Cygwin profile script from doing an automatic `cd ${HOME}`
  CHERE_INVOKING: 1
  CYGWIN:         winsymlinks:native

  # Cygwin package search:  https://cygwin.com/packages/
  # Cygwin package list:    https://cygwin.com/packages/package_list.html
  # Cygwin-official Action: https://github.com/marketplace/actions/install-cygwin-action
  # ** NOTE **: On Cygwin, need to create a symlink for libtermcap.a -> libncurses.a
  #  - https://superuser.com/a/1020342
  CYGWIN_DEPENDS: cygport
  CYGWIN_PACKAGING_DEPENDS: cygport git autoconf automake m4 make binutils gcc-core gcc-g++ gcc-objc bison flex libtool gawk gettext gettext-devel gettext-debuginfo texinfo  file libisl-devel libncurses-devel dejagnu  stow
  CYGWIN_GCC44_BUILD_DEPENDS: libglib2.0-devel libgmp-devel libmpfr-devel libmpc-devel zip unzip
  # Cygwin lacks packages for Mono, so the "gcc44" toolchain set is unsupported unless Mono is built and installed manually
  CYGWIN_GCC44_MISSING_DEPENDS:    mono-runtime libmono-2.0-dev

defaults:
  run:
    shell: bash

jobs:
  build_toolchain_job:
    name:     Cygport Package Generation for ${{ matrix.platform }}
    strategy:
      fail-fast:  false
      matrix:     
        os:       [ "windows-latest" ]
        platform: [ "x86_64", "x86" ]
    runs-on:      ${{ matrix.os }}
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4
      with:
        path: ${{ env.REPO_DIR }}
        # git-restore-mtime-bare uses the ref log to find the correct timestamp
        # for each file. This requires a full git history. The default value (1)
        # creates a shallow checkout.
        fetch-depth: 0

      # Cygwin action docs – https://github.com/marketplace/actions/install-cygwin-action
    - name: Setup Cygwin Environment
      uses: cygwin/cygwin-install-action@v5
      with:
        platform: ${{ matrix.platform }}
        packages: ${{ env.CYGWIN_PACKAGING_DEPENDS }}

      # Run the Cygport steps
    - name: Download the source archive
      run:  cygport $CYGPORT_FILE download

    - name: Prepare the source code
      run:  cygport $CYGPORT_FILE prep

    - name: Compile the source code
      run:  cygport $CYGPORT_FILE compile

    - name: Install the built code to a DestDir
      run:  cygport $CYGPORT_FILE install

    - name: Package the build
      run:  cygport $CYGPORT_FILE package

    - name: List the contents of the generated Cygwin package
      run:  tar --list --file="$PACKAGE_PATH"

    - name: Archive the host installation snapshot tar file
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.PROJECT_NAME }}-${{ matrix.platform }}_${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
        path: "$PACKAGE_PATH"
