name: Cygport Packager

# NOTE: With Cygwin, multi-line values (e.g. run, path) do NOT work
#   due to end-of-line character issues and differences.

# jq -cn --argjson files "$(ls *.cygport | jq --raw-input | jq --slurp --compact-output)" '{file: $files}'

env:
  PACKAGE_NAME:  h8300-hitachi-coff-toolchain
  PACKAGE_BUILD_REQUIRES:  autoconf automake m4 make binutils gcc-core gcc-g++ gcc-objc bison flex libtool gawk gettext gettext-devel gettext-debuginfo texinfo  file libisl-devel libncurses-devel dejagnu

  ## ========================================= ##
  ## NO USER SERVICEABLE PARTS BELOW THIS LINE ##
  ## ========================================= ##
  
  FILE_FILTER:     "*.cygport"
  MATRIX_OS:       '"os": [ "windows-latest" ]'
  MATRIX_PLATFORM: '"platform": [ "x86_64", "x86" ]'
  
  # Cygwin Environment Configuration
  
  # Prevent the Cygwin profile script from doing an automatic `cd ${HOME}`
  CHERE_INVOKING:   1
  # Ensure PATH contains only Cygwin executables
  CYGWIN_NOWINPATH: 1
  # Use native symlinks that Command and PowerShell can understand
  CYGWIN:           winsymlinks:native

  # Cygwin package search:  https://cygwin.com/packages/
  # Cygwin package list:    https://cygwin.com/packages/package_list.html
  # Cygwin-official Action: https://github.com/marketplace/actions/install-cygwin-action
  # NOTE: The "ruby" dependency is needed because "CYGWIN_NOWINPATH"
  #   does not appear to fully work, and Cygport will otherwise fail
  #   as it will find Ruby but it is the GitHub-installed Ruby and not the Cygwin-installed Ruby.
  CYGWIN_WORKFLOW_REQUIRES: cygport jq git tree ruby stow

on:
  workflow_dispatch:
  schedule:
    # Following POSIX cron syntax, run every Monday morning at 5:30 AM UTC
    #   https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron:   '30 5 * * 1'
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  compose_matrix:
    name:     Generate the Job Matrix
    outputs:
      JSON_MATRIX: ${{ steps.generate_json_matrix.outputs.JSON_MATRIX }}

    runs-on:      ubuntu-latest
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4

    - name: Create the JSON for the Job Matrix
      id:   generate_json_matrix
      run:  |
        MATRIX_FILE=$(ls $FILE_FILTER | jq --raw-input | jq --slurp --compact-output)
        JSON_MATRIX="{ $MATRIX_OS, $MATRIX_PLATFORM, \"file\": $MATRIX_FILE }"
        echo "JSON_MATRIX=$JSON_MATRIX"  >>  "$GITHUB_OUTPUT"
        
    - name: Output the generated JSON Matrix
      run:  echo $JSON_MATRIX | jq --slurp .
        

  generate_package:
    name:     Packaging ${{ matrix.file }} for ${{ matrix.platform }}
    needs:    compose_matrix

    strategy:
      fail-fast:  false
      matrix:     ${{ fromJson(needs.compose_matrix.outputs.JSON_MATRIX) }}

    runs-on:      ${{ matrix.os }}
    
    steps:
    - name: Get latest from version control
      uses: actions/checkout@v4

      # Map property name/value pairs to environment variables
    - name: Retrieve properties from file
      run:  echo NAME="$(source "${{ matrix.file }}" && echo $NAME)"  >>  "$GITHUB_ENV"

    - name: Retrieve properties from file
      run:  echo VERSION="$(source "${{ matrix.file }}" && echo $VERSION)"  >>  "$GITHUB_ENV"

    - name: Retrieve properties from file
      run:  echo RELEASE="$(source "${{ matrix.file }}" && echo $RELEASE)"  >>  "$GITHUB_ENV"

    - name: Retrieve properties from file
      run:  echo BUILD_REQUIRES="$(source "${{ matrix.file }}" && echo $BUILD_REQUIRES)"  >>  "$GITHUB_ENV"

    - name: Check for needed properties in Cygport file
      if:   (env.NAME == '') || (env.VERSION == '') || (env.RELEASE == '')
      run:  echo "File \"${{ matrix.file }}\" must include NAME, VERSION, and RELEASE properties" && exit 1

    - name: Report found information
      run:  echo "Found Cygport file \"${{ matrix.file }}\" for $NAME-$VERSION-$RELEASE"

      # Packages for the "x86" platform have a different filename pattern
    - name: Determine the platform-appropriate file string
      if:   matrix.platform != 'x86'
      run:  echo "PLATFORM_FILE_STRING=${{ matrix.platform }}" >> "$GITHUB_ENV"


      # Cygwin action docs – https://github.com/marketplace/actions/install-cygwin-action
    - name: Setup Cygwin Environment
      uses: cygwin/cygwin-install-action@v5
      with:
        platform: ${{ matrix.platform }}
        packages: ${{ env.CYGWIN_WORKFLOW_REQUIRES }} ${{ env.BUILD_REQUIRES }}

      # Run the Cygport steps
    - name: Download the source archive
      run:  cygport "${{ matrix.file }}" download

    - name: Prepare the source code
      run:  cygport "${{ matrix.file }}" prep

    - name: Compile the source code
      run:  cygport "${{ matrix.file }}" compile

    - name: Install the built code to a DestDir
      run:  cygport "${{ matrix.file }}" install

    - name: Package the build
      run:  cygport "${{ matrix.file }}" package

      # Packages for the "x86" platform have a different filename pattern
    - name: Resolve the literal value of the package file path
      run:  echo "PACKAGE_FILE_PATH=$(realpath --relative-to=. --logical --no-symlinks $PACKAGE_PATH/$PACKAGE_FILE)" >> "$GITHUB_ENV"

    - name: List “dist” directory contents
      run:  tree --dirsfirst "$PACKAGE_PATH"

    - name: Archive the host installation snapshot tar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}-${{ matrix.platform }}_${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        path: ${{ env.PACKAGE_FILE_PATH }}
        if-no-files-found: error
        # The artifacts are already compressed, so further compression is superfluous
        compression-level: 0
